# Generated by Django 3.0.3 on 2020-02-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_like_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='star',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
